### Preliminaries

In [1]:
import numpy as np

<br>
<br>

### Random Number Generation Instances

The random integers generation approach illustrated within future learn [is now a legacy approach](https://numpy.org/devdocs/reference/random/generated/numpy.random.randint.html).  The advised approach is detailed at [Random Sampling](https://numpy.org/devdocs/reference/random/index.html#random-sampling-numpy-random).  The latest approach for generating random integers is illustrated herein.  More notes about

 * `default_rng`: https://numpy.org/doc/stable/reference/random/generator.html
 * constant variables: https://www.python.org/dev/peps/pep-0008/#id46

In [2]:
SEED = 5
rng = np.random.default_rng(seed=SEED)

<br>
<br>

### Arithmetic

Hence, 60 rolls of a dice

In [3]:
myrolls = rng.integers(low=1, high=7, size=60)
myrolls

array([5, 5, 1, 5, 3, 4, 4, 2, 6, 1, 2, 3, 4, 3, 1, 1, 1, 1, 1, 6, 2, 4,
       5, 2, 2, 3, 2, 6, 2, 6, 5, 6, 1, 3, 4, 3, 4, 5, 4, 1, 6, 4, 6, 2,
       3, 6, 2, 1, 3, 5, 1, 6, 3, 2, 4, 6, 6, 6, 2, 1], dtype=int64)

In [4]:
np.mean(myrolls)

3.4

In [5]:
np.unique(myrolls, return_counts=True)

(array([1, 2, 3, 4, 5, 6], dtype=int64),
 array([12, 11,  9,  9,  7, 12], dtype=int64))